# preload = ~/.config/hypr/wallpaper/sunset.png
# wallpaper = ~/.config/hypr/wallpaper/sunset.png
#
splash = false
wallpaper {
    monitor = HDMI-A-3
    path = ~/.config/hypr/wallpaper/sunset.png
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = ~/.config/hypr/wallpaper/sunset.png
    fit_mode = cover
}
